name = "Tasmanian"
uuid = "1e81e918-d094-11e8-0e93-1dd8855012cf"
authors = ["Florian Oswald <florian.oswald@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tasmanian_jll = "5b6edb9a-6f5c-5561-95ad-cece0030cdd0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Plots = "0.12.1, 1.39.0"
Tasmanian_jll = "8.0.0"
Test = "1.6.3, 1.10" 
julia = "1.6.3"
